import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server"
import { NuqsAdapter } from "nuqs/adapters/next/app"
import { Providers } from "@/components/providers"
import "./globals.css"

const geist = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
})

export const metadata: Metadata = {
  title: "Slack",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: {
  children: React.ReactNode
}) {
  return (
    <ConvexAuthNextjsServerProvider>
      <html lang="pt-BR">
        <body className={`${geist.variable} ${geistMono.variable} antialiased`}>
          <NuqsAdapter>
            <Providers>
              {children}
            </Providers>
          </NuqsAdapter>
        </body>
      </html>
    </ConvexAuthNextjsServerProvider>
  )
}
